[package]
name = "mandelbrot"
version = "0.1.0"
authors = ["James Seward <james@jamesoff.net>"]
edition = "2018"

[dependencies]
num = "0.1.27"
image = "0.13.0"
crossbeam = "0.2.8"
num_cpus = "1.9.0"
